In [2]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from Adjuct_Memory import memoryManager
from Preprocessing import Data_Preprocessing
import configparser

In [56]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier, GradientBoostingClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score, r2_score,log_loss, confusion_matrix

In [4]:
import mlflow

# AWS account details 

>- Bucket name - mlflow-artifacts-rmte
>- RDS postgre sql - 
    - db instant - mlflow-db-instant
    - Master username - MlflowUser
    - Master password - 1234pass
    - Database port - 5432
    - database name - mlflowDBstore
    - database end point - "mlflow-db-instant.cltodkadxrva.ap-south-1.rds.amazonaws.com"
    
> - AWS access key - AKIAQ7O2DLA4L2JYUDH5
> - VtMUsxPsXZXJJ+VR6Qj4nnzh9s07bwYemxOeDrF5

### Run this command in AWS EC2 instance

mlflow server -h 0.0.0.0 -p 5000 --backend-store-uri postgresql://MlflowUser:1234pass@mlflow-db-instant.cltodkadxrva.ap-south-1.rds.amazonaws.com:5432/mlflowDBstore --default-artifact-root s3://mlflow-artifacts-rmte

In [5]:
#os.environ["AWS_PROFILE"] = "meet9426" # fill in with your AWS profile. More info: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup.html#setup-credentials

TRACKING_SERVER_HOST = "ec2-3-108-227-222.ap-south-1.compute.amazonaws.com" # fill in with the public DNS of the EC2 instance
mlflow.set_tracking_uri(f"http://{TRACKING_SERVER_HOST}:5000")

In [6]:
print(f"tracking URI: '{mlflow.get_tracking_uri()}'")

tracking URI: 'http://ec2-3-108-227-222.ap-south-1.compute.amazonaws.com:5000'


In [7]:
mlflow.list_experiments()

[<Experiment: artifact_location='s3://mlflow-artifacts-rmte/0', experiment_id='0', lifecycle_stage='active', name='Default', tags={}>,
 <Experiment: artifact_location='s3://mlflow-artifacts-rmte/3', experiment_id='3', lifecycle_stage='active', name='GiveMeSomeCredits', tags={}>]

In [8]:
mlflow.get_artifact_uri()

's3://mlflow-artifacts-rmte/0/ea53267961aa4a528895999dbe8ab5c4/artifacts'

In [9]:
config = configparser.ConfigParser()
config.read('config.ini')

['config.ini']

In [10]:
# load dataset
data = pd.read_csv(config['Training_Data']['file_path'] +'\\'+ config['Training_Data']['file_name'])
data_t = pd.read_csv(config['Testing_Data']['file_path'] +'\\'+ config['Testing_Data']['file_name'])
data.head()

Unnamed: 0  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0           1                 1                              0.766127   45   
1           2                 0                              0.957151   40   
2           3                 0                              0.658180   38   
3           4                 0                              0.233810   30   
4           5                 0                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [11]:
# drop id, it is just a number given to identify each house
data.drop(['Unnamed: 0'], axis=1, inplace=True)
data_t.drop(['Unnamed: 0'], axis=1, inplace=True)
data.shape,data_t.shape

((150000, 11), (101503, 11))

In [12]:
train_data = memoryManager.reduce_mem_usage(data)
test_data = memoryManager.reduce_mem_usage(data_t)

Memory usage of dataframe is 12.59 MB
Memory usage after optimization is: 2.72 MB
Decreased by 78.4%
Memory usage of dataframe is 8.52 MB
Memory usage after optimization is: 2.52 MB
Decreased by 70.5%


In [13]:
def data_build(df):
    X = df.drop('SeriousDlqin2yrs',axis=1)
    y = df.SeriousDlqin2yrs
    sc = StandardScaler()
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)    

    return X, y, X_train, y_train, X_test, y_test

In [75]:
def modelling(model, X_train, y_train, X_test, y_test, env = True):
    if env:
        print('I am here')
        model_ = model.fit(X_train, y_train)
        predictions = model_.predict(X_test)
        
        lg = log_loss(y_test,predictions)
        recall = recall_score(y_test,predictions)
        precision = precision_score(y_test,predictions)
        f1 = f1_score(y_test,predictions)
        
#         print("="*100)
#         print('log loss, ', lg)
#         print('Accuracy Score, ', accuracy_score(y_test,predictions))
#         print('Recall Score, ', recall)
#         print('Precision Score, ', precision)
#         print("="*100)
#         print('Confusion Matrix, \n', confusion_matrix(y_test,predictions))
        
        return predictions, lg, recall, precision, f1
        
    else:
        print('I am here_1')
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        model_ = model.fit(X_train, y_train)
        predictions = model.predict_proba(X_test)
    
        return predictions, None, None, None, None , model_

In [15]:
transformed_data = train_data.copy()

In [16]:
train = Data_Preprocessing(transformed_data)

In [17]:
test = Data_Preprocessing(test_data)

In [18]:
transformed_feature = ['SeriousDlqin2yrs',
                       'RevolvingUtilizationOfUnsecuredLines',
                       'Weighted_Delay_sum', 
                       'age',
                       'MonthlyIncome_nolg_', 
                       'DebtRatio', 
                       'NumberOfDependentsTR',
                       'NumberRealEstateLoansOrLinesTR', 
                       'NumberOfOpenCreditLinesAndLoansTR']

In [19]:
train_data_bkp = train.copy()
test_data_bkp = test.copy()

In [20]:
df = train[transformed_feature]

In [37]:
X, y, X_train, y_train, X_test, y_test = data_build(df)

In [25]:
mlflow.set_experiment("GiveMeSomeCredits")

<Experiment: artifact_location='s3://mlflow-artifacts-rmte/3', experiment_id='3', lifecycle_stage='active', name='GiveMeSomeCredits', tags={}>

In [53]:
model_list = [LogisticRegression(),KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),GaussianNB(),XGBClassifier(),LGBMClassifier()]

In [54]:
str(model_class).split('.')[-1].split("'")[0][0:-2]

'LogisticRegression'

In [58]:
for model_class in model_list:
    with mlflow.start_run():
        model_name = str(model_class).split('.')[-1].split("'")[0][0:-2]
        mlflow.set_tag("Model",model_name)
        mlflow.set_tag('Developer','Amit Mane')
        
        print(model_name)
        pred, lg, recall, precision, f1 = modelling(model_class,X_train, y_train, X_test, y_test)
                
        mlflow.log_metric('Log Loss',lg)
        mlflow.log_metric('Recall',recall)
        mlflow.log_metric('Precision',precision)
        mlflow.log_metric('F1',f1)
        
#         mlflow.sklearn.log_model(mlmodel,artifact_path='models')
#         print("Default artifact URI ,", mlflow.get_artifact_uri())

LogisticRegression
I am here
LogisticRegression()
(105000, 8)
(105000,)
log loss,  2.3194712500742893
Accuracy Score,  0.9328444444444445
Recall Score,  0.014168039538714991
Precision Score,  0.589041095890411
Confusion Matrix, 
 [[41935    30]
 [ 2992    43]]
KNeighborsClassifier
I am here
KNeighborsClassifier()
(105000, 8)
(105000,)
log loss,  2.3348277876883947
Accuracy Score,  0.9324
Recall Score,  0.11828665568369028
Precision Score,  0.49517241379310345
Confusion Matrix, 
 [[41599   366]
 [ 2676   359]]
DecisionTreeClassifier
I am here
DecisionTreeClassifier()
(105000, 8)
(105000,)
log loss,  3.5383487423715976
Accuracy Score,  0.8975555555555556
Recall Score,  0.27808896210873146
Precision Score,  0.2586576769843702
Confusion Matrix, 
 [[39546  2419]
 [ 2191   844]]
RandomForestClassifier
I am here
RandomForestClassifier()
(105000, 8)
(105000,)
log loss,  2.2434930495381984
Accuracy Score,  0.9350444444444445
Recall Score,  0.1785831960461285
Precision Score,  0.5576131687242798

In [76]:
df_test = test_data[transformed_feature]
Xtest = df_test.drop('SeriousDlqin2yrs',axis=1)
final_modelwise_prediction = []

In [77]:
df_test.shape

(101503, 9)

In [78]:
for model_class in model_list:
    with mlflow.start_run():
        model_name = str(model_class).split('.')[-1].split("'")[0][0:-2]
        mlflow.set_tag("Model",model_name)
        mlflow.set_tag('Developer','Amit Mane')
        
        print(model_name)
        pred, lg, recall, precision, f1, mlmodel = modelling(model_class,X, y, Xtest, None, False)
        final_modelwise_prediction.append(pred)        
#         mlflow.log_metric('Log Loss',lg)
#         mlflow.log_metric('Recall',recall)
#         mlflow.log_metric('Precision',precision)
#         mlflow.log_metric('F1',f1)
        
        mlflow.sklearn.log_model(mlmodel,artifact_path='models')
        print("Default artifact URI ,", mlflow.get_artifact_uri())

LogisticRegression
I am here_1


EndpointConnectionError: Could not connect to the endpoint URL: "https://mlflow-artifacts-rmte.s3.ap-south-1b.amazonaws.com/3/b5cd15f6b0b842c69fcc07b8ef4b58e7/artifacts/models/conda.yaml"

In [61]:
final_modelwise_prediction

[array([[0.93152739, 0.06847261],
        [0.93637048, 0.06362952],
        [0.94123857, 0.05876143],
        ...,
        [0.96784721, 0.03215279],
        [0.93092539, 0.06907461],
        [0.90260455, 0.09739545]]),
 array([[1. , 0. ],
        [0.8, 0.2],
        [0.8, 0.2],
        ...,
        [0.8, 0.2],
        [1. , 0. ],
        [0.8, 0.2]]),
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[9.99841995e-01, 1.58005345e-04],
        [1.00000000e+00, 0.00000000e+00],
        [1.00000000e+00, 0.00000000e+00],
        ...,
        [9.90000000e-01, 1.00000000e-02],
        [9.10000000e-01, 9.00000000e-02],
        [9.59841995e-01, 4.01580053e-02]]),
 array([[0.86457203, 0.13542797],
        [0.76777683, 0.23222317],
        [0.92240729, 0.07759271],
        ...,
        [0.95688598, 0.04311402],
        [0.98259975, 0.01740025],
        [0.85961051, 0.14038949]]),
 array([[0.929096  , 0.07090399],
   

In [64]:
log_reg = final_modelwise_prediction[0][:,1]
knn_mod = final_modelwise_prediction[1][:,1]
dct_mod = final_modelwise_prediction[2][:,1]
rf_mod = final_modelwise_prediction[3][:,1]
nb_mod = final_modelwise_prediction[4][:,1]
xgb_mod = final_modelwise_prediction[5][:,1]
lgbm_mod = final_modelwise_prediction[6][:,1]

In [68]:
for j,i in enumerate([log_reg,knn_mod,dct_mod,rf_mod,nb_mod,xgb_mod,lgbm_mod]):
    Xtest.loc[:, 'Probability'] = i
    Xtest.loc[:, 'Id'] = range(1,101504)
    
    Xtest[['Id','Probability']].to_csv(f'DataSet/sub_{j}.csv',index=False)